tulips/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path("", views.TulipsView.as_view()),
    path("all_tulips/", views.AllTulipsView.as_view(), name="all_tulips"),
    # path('filter/', views.FilterCategory.as_view(), name='filter'),
    path("add_zakaz/", views.ZakazReview.as_view(), name="add_zakaz"),
    path("<slug:slug>/", views.TulipsDetailView.as_view(), name="tulip_detail"),
    path("review/<int:pk>/", views.AddReview.as_view(), name="add_review"),

]

tulips/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    """Категории"""
    name = models.CharField("Категория", max_length=150)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Tulips(models.Model):
    """Тюльпаны"""
    title = models.CharField("Название", max_length=200)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="tulips_image/")
    price = models.PositiveIntegerField("Цена", default=0)
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField("Черновик", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("tulip_detail", kwargs={"slug": self.url})

    class Meta:
        verbose_name = "Тюльпан"
        verbose_name_plural = "Тюльпаны"


class RatingStar(models.Model):
    """Звезда рейтинга"""
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"


class Rating(models.Model):
    """Рейтинг"""
    ip = models.CharField("IP адрес", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="звезда")
    tulip = models.ForeignKey(Tulips, on_delete=models.CASCADE, verbose_name="тюльпан")

    def __str__(self):
        return f"{self.star} - {self.tulip}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey('self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True)
    tulip = models.ForeignKey(Tulips, verbose_name="тюльпан", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.tulip}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"


class Zakaz(models.Model):
    mail = models.EmailField(blank=False)
    name = models.CharField("Ф.И.О.", max_length=300, blank=False)
    contacts = models.CharField("Телефон", max_length=20, blank=False)
    text = models.TextField(max_length=5000, blank=False)

    def __str__(self):
        return f"{self.name} - {self.contacts}"

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

tulips/forms.py
from django import forms
from .models import Reviews, Zakaz, Rating, RatingStar



class ReviewForm(forms.ModelForm):
    """Форма отзывов"""
    class Meta:  # указываем от какой модели нам нужно строить форму
        model = Reviews
        # указываем поля из модели которые мы хотим видеть в нашей форме
        fields = ("name", "email", "text")


class ZakazForm(forms.ModelForm):
    class Meta:
        model = Zakaz
        fields = ("mail", "name", "contacts", "text")


class RatingForm(forms.ModelForm):
    """Форма добавления рейтинга"""
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star",)

tulips/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View, TemplateView
from .models import Tulips, Category
from django.http import HttpResponseRedirect
# Create your views here.
from .forms import ReviewForm, ZakazForm, RatingForm


class GategoriesList:
    def get_categor(self):
        return Category.objects.all()

    def get_tulip(self):
        return Tulips.objects.filter(draft=False)


# class FilterCategory(GategoriesList, ListView):
#     """Фильтр тюльпанов"""
#     def get_queryset(self):
#         queryset = Tulips.objects.filter(category__in=self.request.GET.getlist("category"))
#         return queryset

    # Тут мы фильтруем и если категори которая приходит с фронта находится, мы достаем все значение тбльпана по тайтлу


class TulipsView(GategoriesList, ListView):
    """Список тюльпанов"""
    model = Tulips
    # queryset = Tulips.objects.all()
    queryset = Tulips.objects.filter(draft=False)  # Фильтруем и не выводим поле с черновиками
    template_name = "tulips/index.html"
    # paginate_by = 6


class AllTulipsView(GategoriesList, ListView):
    """Все позиции цветов"""
    model = Tulips
    queryset = Tulips.objects.filter(draft=False)
    template_name = "tulips/all_tulips.html"
    context_object_name = 'all_tulips'
    paginate_by = 6


class TulipsDetailView(DetailView):
    """Полное описание цветка"""
    model = Tulips
    slug_field = "url"
    template_name = "tulips/tulips.html"
    context_object_name = "tulip"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["star_form"] = RatingForm()
        return context


# class AddReview(View):
#     """Отзывы"""
#     def post(self, requests, pk):
#         form = ReviewForm(requests.POST)
#         if form.is_valid():
#             form = form.save(commit=False)  # говорим что мы хотим приостановить сохранение нашей
#             # формы, чтоб внести в неё некие изменения
#             form.tulip_id = pk  # в поле tulips мы должны указать объект к которому хотим привязаться
#             # но так как у нас есть только id (pk) нашего тюльпана, напрямую в это поле мы не можем передать данное
#             # число, мы должны сюда передавать обьект нашего цветка но можем через _id указать наше значение
#             form.save() # теперь данные с формы будут записаны в базу (tulips_id мы взяли из нащей базы tulips_reviews)
#         return redirect("/")


class AddReview(View):
    """Отзывы второй вариант"""
    def post(self, requests, pk):
        form = ReviewForm(requests.POST)
        tulip = Tulips.objects.get(id=pk)  # делая запрос в БД и найди наш фильм по id мы получаем
        # наш объект тюльпана
        if form.is_valid():
            form = form.save(commit=False)  # говорим что мы хотим приостановить сохранение нашей
            # формы, чтоб внести в неё некие изменения
            form.tulip = tulip  # тут мы присваиваем наш объект
            if requests.POST.get("parent", None):
                form.parent_id = int(requests.POST.get("parent"))
                """parent это имя нашего поля в верстке, если оно будет мы выполним код, если None то ничего не произойдет
                далее parent_id (id потому что мы будем добавлять число а не объект), мы достаем значение нашего ключа parent
                но так как оно строковое мы оборачиваем его в инт"""
            form.save()
        return redirect(tulip.get_absolute_url())


class ZakazReview(View):
    def post(self, request):
        if request.method == "POST":
            form = ZakazForm(request.POST)
            if form.is_valid():
                form.save()
            return HttpResponseRedirect("/")
        # else:
        #     form = ZakazForm()
        # return render(request, "include/footer.html", {"form": form})

# class TulipsView(View):
#     """Список тюльпанов"""
#     def get(self, requests):
#         tulips = Tulips.objects.all()
#         return render(requests, "tulips/index.html", {"tulips_list": tulips})
#
#
#
# class TulipsDetailView(View):
#     """Полное описание цветка"""
#     def get(self, requests, slug):
#         tulip = Tulips.objects.get(url=slug)
#         return render(requests, "tulips/tulips.html", {"tulip": tulip})

templates/tulips/all_tulips.html
<!DOCTYPE html>
{% load static %}

<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Тюльпаны из Голландии {% endblock title %}</title>
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css">
    <script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;400;700&family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    <link rel="stylesheet" href="{% static 'css/hover-min.css' %}">
    <!-- <link rel="shortcut icon" href="img/favicon2.ico" type="image/x-icon"> -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
        .tulip__img {
            border-top-left-radius: 15px;
            border-top-right-radius: 15px;
        }
    </style>

  </head>
{% include 'include/header.html' %}

<section class="container section__hero__all">
    <h1 class="hero__title">
        Специальное предложение
    </h1>
    <p class="hero__text">
        Получите скидку при заказе от 1000 штук
    </p>
    <div class="hero__btn-container">
        <button class="btn-reser btn hvr-shutter-out-horizontal hero__btn">
            <a class="btn__link" href="#">Заказать прямо сейчас</a>
        </button>
    </div>
</section>
 <section class="container section__all__tulips">
    <div class="container flex services__container">
        {% for tulip in all_tulips %}
            <article class="sevices__article-all">
                <img class="tulip__img" src="{{ tulip.image.url }}" alt="tulips image">
                <h3 class="article__title">
                    <a href="{{ tulip.get_absolute_url }}">{{ tulip.title }}</a>
                </h3>
                <div class="services__star">
                    <span class="article_price">{{ tulip.price }} р/шт</span>
                    <img class="star" src="{% static 'img/star.svg' %}" alt="">
                    <img class="star" src="{% static 'img/star.svg' %}" alt="">
                    <img class="star" src="{% static 'img/star.svg' %}" alt="">
                    <img class="star" src="{% static 'img/star.svg' %}" alt="">
                    <img class="star" src="{% static 'img/star.svg' %}" alt="">
                </div>
                <p class="article__about">{{ tulip.description|safe }}</p>
                <button class="btn-reset btn hvr-shutter-out-horizontal price__button">
                    <a class="price__link" href="#">Заказать</a>
                </button>
            </article>
        {% endfor %}
    </div>
 </section>
{% include 'include/footer.html' %}







{#</main>#}

templates/tulips/base.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {% endblock title %}
{% block header %}
    <header class="container header__container">
    <nav class="header__nav">
        <a class="logo__image-href" href="#">
            <img class="logo__image" src="{% static 'img/logo_1.png' %}" alt="image_logo">
        </a>
        <ul class="header__list list-reset">
            <li class="header__list-item">
                <a class="header__link" href="#">
                    На главную
                </a>
            </li>
            <li class="header__list-item">
                <a class="header__link" href="#">
                    Галерея
                </a>
            </li>
            <li class="header__list-item">
                <a class="header__link" href="#">
                    О нас
                </a>
            </li>
            <li class="header__list-item">
                <a class="header__link" href="#">
                    Контакты
                </a>
            </li>
            <li class="header__list-item">
                <a class="header__link" href="#">
                    Отзывы
                </a>
            </li>
        </ul>
    </nav>
</header>
{% endblock header %}

{% block content %}
    {% block heroall %}
<section class="container section__hero__all">
    <h1 class="hero__title">
        Специальное предложение
    </h1>
    <p class="hero__text">
        Получите скидку при заказе от 1000 штук
    </p>
    <div class="hero__btn-container">
        <button class="btn-reser btn hvr-shutter-out-horizontal hero__btn">
            <a class="btn__link" href="#">Заказать прямо сейчас</a>
        </button>
    </div>
</section>
    {% endblock heroall %}

        {% include 'include/gategory.html' %}
    </section>
    {% include 'include/pagination.html' %}
    {% block tulip %}
    {% endblock tulip %}
{% endblock content %}

templates/tulips/index.html
{% extends 'tulips/base.html' %}
{% load static %}
{% block content %}
<main>
    <section class="container section__hero">
        <h1 class="hero__title animate__animated animate__backInUp">
            Тюльпаны из Голландии
        </h1>
        <p class="hero__text animate__animated animate__backInUp">
            Продажа оптом по Москве<br>и Московской области
        </p>
        <div class="hero__btn-container">
            <button class="btn-reser hvr-shutter-out-horizontal hero__btn">
                <a class="btn__link" href="#">Заказать прямо сейчас</a>
            </button>
        </div>
    </section>
    <section class="container section__services">
        <h2 class="sevices__title">
            Эксклюзивные предложения от наших поставщиков из Голландии
        </h2>
        <a class="collection__link" href="{{ '/all_tulips/' }}">
            <svg width="35" height="8" viewBox="0 0 35 8" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M34.3536 4.35355C34.5488 4.15829 34.5488 3.84171 34.3536 3.64645L31.1716 0.464466C30.9763 0.269204 30.6597 0.269204 30.4645 0.464466C30.2692 0.659728 30.2692 0.976311 30.4645 1.17157L33.2929 4L30.4645 6.82843C30.2692 7.02369 30.2692 7.34027 30.4645 7.53553C30.6597 7.7308 30.9763 7.7308 31.1716 7.53553L34.3536 4.35355ZM0 4.5H34V3.5H0L0 4.5Z" fill="black"/>
            </svg>
            Смотреть всю коллекцию
        </a>

        <div class="container flex services__container">
            {% for tulip in tulips_list %}
                <article class="sevices__article">
                    <img class="tulip__img" src="{{ tulip.image.url }}" alt="tulips image">
                    <h3 class="article__title">
                        <a href="{{ tulip.get_absolute_url }}">{{ tulip.title }}</a>
{#                            <a href="{% url 'tulip_detail' tulip.url %}">{{ tulip.title }}</a> альтернативный метод подстановки урла#}
                    </h3>
                    <div class="services__star">
                        <span class="article_price">{{ tulip.price }} р/шт</span>
                        <img class="star" src="{% static 'img/star.svg' %}" alt="">
                        <img class="star" src="{% static 'img/star.svg' %}" alt="">
                        <img class="star" src="{% static 'img/star.svg' %}" alt="">
                        <img class="star" src="{% static 'img/star.svg' %}" alt="">
                        <img class="star" src="{% static 'img/star.svg' %}" alt="">
                    </div>
                    <p class="article__about">{{ tulip.description|safe }}</p>
                    <button class="btn-reset hvr-shutter-out-horizontal btn price__button">
                        <a class="price__link" href="#">Заказать</a>
                    </button>
                </article>
            {% endfor %}
        </div>

    </section>
    <section class="container section__gallery">
        <h2 class="gallery__title" id="gallery__title-id">
            Галерея от наших поставщиков
        </h2>
        <!-- Slider main container -->
        <div class="swiper">
            <!-- Additional required wrapper -->
            <div class="swiper-wrapper">
            <!-- Slides -->
            <div class="swiper-slide">
                <img src="{% static 'img/tulips_1.jpeg' %}" alt="tulips gallery">
            </div>
            <div class="swiper-slide">
                <img src="{% static 'img/tulips_2.jpeg' %}" alt="tulips gallery">
            </div>
            <div class="swiper-slide">
                <img src="{% static 'img/tulips_3.jpeg' %}" alt="tulips gallery">
            </div>
            <div class="swiper-slide">
                <img src="{% static 'img/tulips_5.jpeg' %}" alt="tulips gallery">
            </div>
            <div class="swiper-slide">
                <img src="{% static 'img/tulips_6.jpeg' %}" alt="tulips gallery">
            </div>
            <div class="swiper-slide">
                <img src="{% static 'img/tulips_7.jpeg' %}" alt="tulips gallery">
            </div>
            <div class="swiper-slide">
                <img src="{% static 'img/tulips_9.jpeg' %}" alt="tulips gallery">
            </div>
            <div class="swiper-slide">
                <img src="{% static 'img/tulips_10.jpeg' %}" alt="tulips gallery">
            </div>
            ...
            </div>
            <!-- If we need pagination -->
            <div class="swiper-pagination"></div>

            <!-- If we need navigation buttons -->
            <div class="swiper-button-prev"></div>
            <div class="swiper-button-next"></div>

            <!-- If we need scrollbar -->
            <!-- <div class="swiper-scrollbar"></div> -->
        </div>
    </section>
    <section class="container section__about">
        <h2 class="about__title">О нас</h2>
        <p class="about__text">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque sequi id placeat quibusdam pariatur alias at aspernatur nemo quas cumque magni, repellat perferendis maxime odit ea non aliquid illo assumenda.
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ducimus aperiam quisquam dolores ipsa eligendi maxime, ut voluptate cumque ad voluptatem est distinctio non, eaque nemo a iusto illo harum illum.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita saepe veritatis asperiores, perferendis eos praesentium blanditiis exercitationem illo, autem nulla assumenda libero quae rem ab iste vitae qui, repellendus veniam?
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam aliquam assumenda dolorum eligendi nostrum sit alias, vitae doloribus corrupti nobis blanditiis est voluptate eum iste! Atque aperiam tempora inventore necessitatibus. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis esse nihil ea consequatur quisquam cupiditate suscipit, illum porro dolorem ex inventore nobis deserunt ipsa non odit dolor tempora officiis dolores.
        </p>
    </section>
    <section class="container section__question">
        <h2 class="question__title">
            Часто задаваемые вопросы
        </h2>
        <div class="accordion">
            <div class="contentBx">
                <div class="label">
                    Из чего формируется конечная стоимость доставки?
                </div>
                <div class="content">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus qui, sapiente tempore veniam voluptate ut error, blanditiis labore nisi natus iste quaerat reiciendis dicta eaque. Reprehenderit, quos veniam? Facere, ad!
                </div>
            </div>
            <div class="contentBx">
                <div class="label">
                    Как настоящие голландские тюльпаны попадают в нашу страну?
                </div>
                <div class="content">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus qui, sapiente tempore veniam voluptate ut error, blanditiis labore nisi natus iste quaerat reiciendis dicta eaque. Reprehenderit, quos veniam? Facere, ad!
                </div>
            </div>
            <div class="contentBx">
                <div class="label">
                    Я выбираю между разными оптовыми поставщиками. В чём ваше отличие?
                </div>
                <div class="content">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus qui, sapiente tempore veniam voluptate ut error, blanditiis labore nisi natus iste quaerat reiciendis dicta eaque. Reprehenderit, quos veniam? Facere, ad!
                </div>
            </div>
            <div class="contentBx">
                <div class="label">
                    У каких поставщиков Вы заказываете цветы и почему у Вас выгодная цена?
                </div>
                <div class="content">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus qui, sapiente tempore veniam voluptate ut error, blanditiis labore nisi natus iste quaerat reiciendis dicta eaque. Reprehenderit, quos veniam? Facere, ad!
                </div>
            </div>
            <div class="contentBx">
                <div class="label">
                    Могу ли я вернуть деньги на каком-либо из этапов доставки?
                </div>
                <div class="content">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus qui, sapiente tempore veniam voluptate ut error, blanditiis labore nisi natus iste quaerat reiciendis dicta eaque. Reprehenderit, quos veniam? Facere, ad!
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock content %}

templates/tulips/tulips.html
{% extends 'tulips/base.html' %}
{% block title %} {{ tulip.title }} {% endblock title %}
{% load static %}
{% block tulip %}

        <section class="container section__tulip animate__animated animate__backInRight">
            <div class="container__tulip">
                <article class="sevices__article-tulip">
                    <img class="tulip__img-info" src="{{ tulip.image.url }}" alt="tulips image">
                    <h3 class="article__title-info animate__animated animate__backInRight">
                        {{ tulip.title }}
                    </h3>
                    <div class="services__star animate__animated animate__backInRight">
                        <span class="article_price-info animate__animated animate__backInRight">{{ tulip.price }} р/шт</span>
                        <img class="star" src="{% static 'img/star.svg' %}" alt="">
                        <img class="star" src="{% static 'img/star.svg' %}" alt="">
                        <img class="star" src="{% static 'img/star.svg' %}" alt="">
                        <img class="star" src="{% static 'img/star.svg' %}" alt="">
                        <img class="star" src="{% static 'img/star.svg' %}" alt="">
                    </div>
                    <p class="article__about-info animate__animated animate__backInRight">{{ tulip.description|safe }}</p>
                    <form class="tulip__form animate__animated animate__backInRight" action="#" method="post">
                        <input class="tulip__input" type="number" name="number" placeholder="1" required>
                        <button class="btn-reset btn price__button hvr-shutter-out-horizontal">
                            <a class="price__link" href="#">Заказать</a>
                        </button>
                    </form>
                    <div class="partners animate__animated animate__backInRight">
                        <img class="partners__img" width="160" height="100" src="{% static 'img/tinkof.svg' %}" alt="">
                        <img class="partners__img" width="100" height="100" src="{% static 'img/visa.svg' %}" alt="">
                        <img class="partners__img" width="80" height="90" src="{% static 'img/mastercard.svg' %}" alt="">
                        <img class="partners__img" width="120" height="110" src="{% static 'img/halva.svg' %}" alt="">
                    </div>
                </article>
                                <div class="container__comment">
                    <h3 class="comment__title">
                        Оставить отзыв
                    </h3>
                    <form class="tulip__form__commentar" action="{% url 'add_review' tulip.id %}" method="post" id="formReview">
                        {% csrf_token %}
                        <input type="hidden" name="parent" id="contactparent" value="">
{#                        передаем ID того отзыва на который хотим ответить, тоесть РОДИТЕЛЯ#}
                        <input class="footer__input comment_input" type="text" name="name" placeholder="Имя*" required>
                        <input class="footer__input comment_input" type="email" name="email" placeholder="E-mail">
                        <textarea class="footer__input footer__input-text comment__text" id="contactcomment" type="text" name="text" placeholder="Сообщение"></textarea>
                        <button class="btn-reset btn footer__btn hvr-shutter-out-horizontal">Отправить</button>
                    </form>
                </div>
                {% for review in tulip.reviews_set.all %}
                    <div class="container container__comment-user">
                        <article class="artic__coment">
                            <img width="60" height="60" src="/img/image_1.png" alt="">
                        <h4 class="user__name">{{ review.name }}</h4>
                        <p class="user__comment">{{ review.text }}</p>
                        </article>
                        <a href="#formReview" onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>
{#                    addReview передаем имя и ID пользователя на комент которого хотим ответить#}
                    </div>
                {% endfor %}
            </div>
        </section>
        <script>
        function addReview(name, id) {
            document.getElementById("contactparent").value = id;
            document.getElementById("contactcomment").innerText = `${name}, `
        }
        </script>
{% endblock tulip %}

templates/tulips/tulips_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for tulip in tulips_list %}
    {{ tulip.title }}
{% endfor %}
</body>
</html>